Master
JKSH/QtSdkRepoChooser pull request #2
Opened 2016-09-23 15:05 UTC by FlorentUguet

Added fixes to handle continental servers along with worldwide servers

2016-09-24 01:00 UTC, JKSH commented on src/downloader.cpp
> +        if(page.contains("mirrors in other countries, but same continent"))
Please add a space after the `if`.

2016-09-24 01:00 UTC, JKSH commented on src/downloader.cpp
> +        QStringList tmp;
Please indent using tabs ('\t') instead of spaces.

2016-09-24 01:03 UTC, JKSH commented on src/downloader.cpp
> +            //Handles continental servers if existing
Please add a space after the `//`.

2016-09-24 01:03 UTC, JKSH commented on src/downloader.cpp
> +            //Handles worldwide servers if no continental server was found
Please add a space after the `//`.

2016-09-24 01:12 UTC, JKSH requested changes
Hi @FlorentUguet, thank you for improving the mirror extraction mechanism!

Please follow the style of the existing code:
- Indent using tabs ('\t') instead of spaces.
- Have a space after `if` and `\\`

Please also squash your 3 commits into 1, since they are part of the same change (it's ok to `--force` a push to this repo)

2016-09-24 01:12 UTC, JKSH commented on src/downloader.cpp
> +        QStringList tmp = page.split("mirrors in other countries, but same continent");
Please indent using tabs ('\t') instead of spaces.

2016-09-25 20:42 UTC, FlorentUguet commented
Thanks for the info, I'm working on it and it should be done quickly

2016-09-30 00:23 UTC, merged

2016-09-30 00:24 UTC, JKSH commented
Thank you for your contribution!